### ISSUE TITLE
Project Blueprints - A todo list.

### ISSUE THREAD

**Issue by AlgorithmX2** [ChiselsAndBits/Chisels-and-Bits#337]
Code:
- [x] Creative Bit Nudging for Wrench
- [x] Capture Blue Prints without c&b.share Command
- [ ] Place Full Blocks if you have them ( conserve chisel damage this way )
- [x] Reasonable notifications of missing bits and chisels.
- [ ] Avoid Entity Rendering, its requires that the chunk is visible, which makes it broken for blueprints.
- [x] Upload to PasteBin

Localization Strings:
- [x] Localization for blue print related functions.
- [x] Localization for wrench related functions.
- [x] Localization for ~~hammer~~Mallet

Art:
- [x] ~~Hammer~~Mallet - Item Sprite
- [x] Wrench - Rotate - Icon
- [x] Wrench - Bit Nudge - Icon
- [x] Wrench - Block Nudge - Icon

Testing:
- [ ] Basic Multiplayer Tests
- [ ] Public Beta?

Subject to change, I think this is mostly accurate.
